/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddProduct.java
 *
 * Created on 3 Jan, 2019, 11:40:22 AM
 */
package javaapplication3;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import net.proteanit.sql.DbUtils;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;

/**
 *
 * @author J Suryam
 */
public class AddProduct extends javax.swing.JDialog {

    Connection connection=null;
    Statement st=null;
    PreparedStatement ps=null;
    ResultSet set=null;
    CommonMethodClass cms=new CommonMethodClass("");
    
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form AddProduct */
    public AddProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        
        showProductData("PRODUCT_NAME","");
        cms.generateUniqueID("PRODUCT", "UID");
        product_id.setText(cms.id);
        cms.tableHeaderSettings(product_table);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column)
            {
                Component c = super.prepareRenderer(renderer, row, column);

                //  Alternate row color

                if (!isRowSelected(row))
                c.setBackground(row % 2 == 0 ? getBackground() : cms.light1);

                return c;
            }
        };
        ;
        jPanel3 = new javax.swing.JPanel();
        product_id = new javax.swing.JTextField();
        product_name = new javax.swing.JTextField();
        product_discription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        product_uom = new javax.swing.JComboBox();
        product_hsncode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        product_unitprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        product_discount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        product_gst_tax = new javax.swing.JComboBox();
        close_label = new javax.swing.JLabel();
        save_label = new javax.swing.JLabel();
        barcode_search = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jButton1.setText("Save");

        setTitle("Add Customer/Client");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(-1,true));
        jPanel1.setOpaque(false);

        jLabel1.setBackground(cms.light1);
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Product");
        jLabel1.setOpaque(true);

        jPanel2.setOpaque(false);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        product_table.setFont(new java.awt.Font("SansSerif", 0, 12));
        product_table.setForeground(new java.awt.Color(-12566464,true));
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        product_table.setGridColor(cms.light2);
        product_table.setRowHeight(20);
        product_table.setSelectionBackground(cms.light3);
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
        });
        product_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(product_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        product_id.setFont(new java.awt.Font("Dialog", 0, 12));
        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });

        product_name.setFont(new java.awt.Font("Dialog", 0, 12));
        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });

        product_discription.setFont(new java.awt.Font("Dialog", 0, 12));
        product_discription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_discriptionActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID / Barcode :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Product Name :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Product Discription");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("UOM");

        product_uom.setEditable(true);
        product_uom.setFont(new java.awt.Font("Dialog", 0, 12));
        product_uom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pcs.", "Kgs", "gms", "Lts" }));

        product_hsncode.setFont(new java.awt.Font("Dialog", 0, 12));
        product_hsncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_hsncodeActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("HSN Code");

        product_unitprice.setFont(new java.awt.Font("Dialog", 0, 12));
        product_unitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_unitpriceActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Unit Price");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tax (GST %)");

        product_discount.setFont(new java.awt.Font("Dialog", 0, 12));
        product_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_discountActionPerformed(evt);
            }
        });
        product_discount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                product_discountFocusLost(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Discount %");

        product_gst_tax.setFont(new java.awt.Font("Dialog", 0, 12));
        product_gst_tax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "12", "18", "28" }));

        close_label.setFont(new java.awt.Font("Dialog", 0, 14));
        close_label.setForeground(new java.awt.Color(-8355712,true));
        close_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        close_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/images/cancel.png"))); // NOI18N
        close_label.setText("Close");
        close_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_labelMouseClicked(evt);
            }
        });

        save_label.setFont(new java.awt.Font("Dialog", 0, 14));
        save_label.setForeground(new java.awt.Color(-8355712,true));
        save_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        save_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/images/save.png"))); // NOI18N
        save_label.setText("Save");
        save_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_labelMouseEntered(evt);
            }
        });
        save_label.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                save_labelFocusLost(evt);
            }
        });

        barcode_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/images/magnifier.png"))); // NOI18N
        barcode_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barcode_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barcode_searchMouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/images/magnifier.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/images/magnifier.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barcode_search))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(save_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(product_unitprice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(product_hsncode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(product_uom, javax.swing.GroupLayout.Alignment.LEADING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(product_gst_tax, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(product_discount, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                .addComponent(close_label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(product_discription, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcode_search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(product_name)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addComponent(product_discription, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_uom)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_hsncode)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_unitprice)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(product_gst_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(product_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(close_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(cms.light3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(672, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_idActionPerformed

private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_nameActionPerformed

private void product_discriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_discriptionActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_discriptionActionPerformed

private void product_hsncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_hsncodeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_hsncodeActionPerformed

private void product_unitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_unitpriceActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_unitpriceActionPerformed

private void product_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_discountActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_product_discountActionPerformed

private void close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_labelMouseClicked
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_close_labelMouseClicked

private void save_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_labelMouseClicked
// TODO add your handling code here:
    insertIntoProduct();
}//GEN-LAST:event_save_labelMouseClicked

private void save_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_labelMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_save_labelMouseEntered

private void product_discountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_product_discountFocusLost
// TODO add your handling code here:
    save_label.grabFocus();
    save_label.setOpaque(false);
    save_label.setBackground(cms.light3);
    save_label.setForeground(new Color(0,153,102));
    
}//GEN-LAST:event_product_discountFocusLost

private void save_labelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_save_labelFocusLost
// TODO add your handling code here:
//    close_label.grabFocus();
//    close_label.setOpaque(false);
//    close_label.setBackground(cms.light3);
//    close_label.setForeground(new Color(0,153,102));
}//GEN-LAST:event_save_labelFocusLost

private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
// TODO add your handling code here:
    
}//GEN-LAST:event_jScrollPane1MouseClicked

private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
// TODO add your handling code here:
    
    String rowID=product_table.getValueAt(product_table.getSelectedRow(), 0).toString();
    fetchProductData(rowID);
}//GEN-LAST:event_product_tableMouseClicked

private void product_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_tableKeyReleased
// TODO add your handling code here:
    String rowID=product_table.getValueAt(product_table.getSelectedRow(), 0).toString();
    fetchProductData(rowID);
}//GEN-LAST:event_product_tableKeyReleased

private void barcode_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcode_searchMouseEntered
// TODO add your handling code here:
  
}//GEN-LAST:event_barcode_searchMouseEntered
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    
        public void showProductData(String where, String like)
    {
        try {
            connection=ConnectionManager.getConnection();
        String query="SELECT ID,UID ,"
                + "PRODUCT_NAME ,"
                + "DISCTIPTION ,"
                + "UOM ,HSNCODE as HSN ,"
                + "UNIT_PRICE as Price,"
                + "GST_TAX TAX,"
                + "DISCOUNT as DISC FROM PRODUCT  where "+where+" like '"+"%"+like+"%"+"' order by ID";
            System.out.println(query);
        st=connection.createStatement();
        set=st.executeQuery(query);
        product_table.setModel(DbUtils.resultSetToTableModel(set));
        tableColumnSize();
        } catch (Exception e) {
            e.printStackTrace();
        }finally
        {
            try {
                connection.close();
                st.close();
                set.close();
            } catch (Exception e) {
            }
        }
    }
   
    public void fetchProductData(String id)
    {
        
        String query="select * from PRODUCT  where ID='"+id+"'";
        System.out.println(query);
        try {
            connection=ConnectionManager.getConnection();
            st=connection.createStatement();
            set=st.executeQuery(query);
            if(set.next())
            {
            product_id.setText(set.getString(2));
            product_name.setText(set.getString(3));
            product_discription.setText(set.getString(4));
            product_uom.setSelectedItem(set.getString(5));
            product_hsncode.setText(set.getString(6));
            product_unitprice.setText(set.getString(7));
            product_gst_tax.setSelectedItem(set.getString(8).toString());
            product_discount.setText(set.getString(9));
            
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally
        {
            try {
                connection.close();
                st.close();
                set.close();
            } catch (Exception e) {
            }
        }

    }
     
    public void updateProductData(String column,String id)
    {
        String query="update PRODUCT "
                + "set uid=?,"
                + "PRODUCT_NAME =?,"
                + "DISCTIPTION  =?,"
                + "UOM  =?,"
                + "HSNCODE  =?,"
                + "UNIT_PRICE  =?,"
                + "GST_TAX  =?,"
                + "DISCOUNT  =? "
                + "where "+column+" =?";
        try {
            connection=ConnectionManager.getConnection();
            ps=connection.prepareStatement(query);

            ps.setString(1, product_id.getText());
            ps.setString(2, product_name.getText());
            ps.setString(3, product_discription.getText());
            ps.setString(4, product_uom.getSelectedItem().toString());
            ps.setString(5, product_hsncode.getText());
            ps.setString(6, product_unitprice.getText());
            ps.setString(7, product_gst_tax.getSelectedItem().toString());
            ps.setString(8, product_discount.getText());
            ps.setString(9, id);
            int i=ps.executeUpdate();
            if(i>0)
            {
            JOptionPane.showMessageDialog(this, "Product data updated successful","successful",JOptionPane.INFORMATION_MESSAGE,cms.icon);
            showProductData("PRODUCT_NAME","");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally
        {
            try {
                connection.close();
                ps.close();
            } catch (Exception e) {
            }
        }
    }
            
      private void tableColumnSize()
	{

			product_table.getColumnModel().getColumn(1).setPreferredWidth(100);
			product_table.getColumnModel().getColumn(2).setPreferredWidth(150);
			product_table.getColumnModel().getColumn(3).setPreferredWidth(150);
			product_table.getColumnModel().getColumn(4).setPreferredWidth(60);     
                        product_table.getColumnModel().getColumn(5).setPreferredWidth(60);
                        product_table.getColumnModel().getColumn(6).setPreferredWidth(80);
                        product_table.getColumnModel().getColumn(7).setPreferredWidth(60);
                        product_table.getColumnModel().getColumn(8).setPreferredWidth(60);
                        product_table.getColumnModel().getColumn(0).setMinWidth(0);
                        product_table.getColumnModel().getColumn(0).setMaxWidth(0);
                        product_table.getColumnModel().getColumn(0).setWidth(0);

                        

		
		DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
		rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
		for(int i=6; i<=8;i++)
		{
			product_table.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
		}
		JTableHeader header = product_table.getTableHeader();
		header.setPreferredSize(new Dimension(100, 32));
		
		
		
		
		
	}
        
    public void insertIntoProduct()
    {
        try {
            String query="select * from product where uid='"+product_id.getText()+"'";
            connection=ConnectionManager.getConnection();
            st=connection.createStatement();
            set=st.executeQuery(query);
            if(set.next())
            {
               int reply = JOptionPane.showConfirmDialog(this, "Do you want to update "+product_id.getText()+" data ?", "Confirm?",  JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                {
                     updateProductData("UID", product_id.getText());
                     showProductData("PRODUCT_NAME","");
//                     clearFields();
                }else
                {
        String query1="insert into product values (?,?,?,?,?,?,?,?,?)";
        try {
            connection=ConnectionManager.getConnection();
            ps=connection.prepareStatement(query1);
            ps.setString(1, cms.csdf.format(new Date()));
            ps.setString(2, product_id.getText());
            ps.setString(3, product_name.getText());
            ps.setString(4, product_discription.getText());
            ps.setString(5, product_uom.getSelectedItem().toString());
            ps.setString(6, product_hsncode.getText());
            ps.setString(7, product_unitprice.getText());
            ps.setString(8, product_gst_tax.getSelectedItem().toString());
            ps.setString(9, product_discount.getText());
            int i=ps.executeUpdate();
            if(i>0)
            {
            JOptionPane.showMessageDialog(this,"Done", "Product added successful",JOptionPane.INFORMATION_MESSAGE,cms.icon);
            showProductData("PRODUCT_NAME","");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally
        {
            try {
                connection.close();
                ps.close();
            } catch (Exception e) {
            }
        } 
                }
            }
          
        } catch (Exception e) {
        }
       
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel barcode_search;
    public javax.swing.JLabel close_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField product_discount;
    public javax.swing.JTextField product_discription;
    public javax.swing.JComboBox product_gst_tax;
    public javax.swing.JTextField product_hsncode;
    public javax.swing.JTextField product_id;
    public javax.swing.JTextField product_name;
    private javax.swing.JTable product_table;
    public javax.swing.JTextField product_unitprice;
    public javax.swing.JComboBox product_uom;
    public javax.swing.JLabel save_label;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
