/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Roots.java
 *
 * Created on 21 Jan, 2019, 10:15:59 AM
 */
package javaapplication3;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author J Suryam
 */
public class Roots extends javax.swing.JFrame {

    CommonMethodClass cms=new CommonMethodClass("Pale Blue");
    /** Creates new form Roots */
    public Roots() {
        
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new javax.swing.JLabel();
        theme_combo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        button_addCustomer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(-1,true));
        jPanel1.setOpaque(false);

        button1.setBackground(cms.light2);
        button1.setFont(new java.awt.Font("Dialog", 0, 18));
        button1.setForeground(new java.awt.Color(-1,true));
        button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button1.setText("Invoice");
        button1.setBorder(javax.swing.BorderFactory.createLineBorder(cms.light2, 2));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setOpaque(true);
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
        });

        theme_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pale Blue", "Sky Blue", "Green", "Orange", "Grey" }));
        theme_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theme_comboActionPerformed(evt);
            }
        });

        jLabel1.setText("Theme");

        button_addCustomer.setBackground(cms.light2);
        button_addCustomer.setFont(new java.awt.Font("Dialog", 0, 18));
        button_addCustomer.setForeground(new java.awt.Color(-1,true));
        button_addCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_addCustomer.setText("Add Customer");
        button_addCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(cms.light1));
        button_addCustomer.setOpaque(true);
        button_addCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_addCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_addCustomerMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(cms.light3);
        jLabel2.setText("Business to Business (B2B)");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(cms.light3);
        jLabel3.setText("Business to Customer (B2C)");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(667, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(theme_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button_addCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(theme_combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_addCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(234, 234, 234))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(858, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
// TODO add your handling code here:
    button1.setBackground(cms.light2);
    button1.setForeground(Color.WHITE);
}//GEN-LAST:event_button1MouseExited

private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
// TODO add your handling code here:
    button1.setBackground(cms.light3);
    button1.setForeground(Color.WHITE);
    
}//GEN-LAST:event_button1MouseEntered

private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
// TODO add your handling code here:
   Dashboard board=new Dashboard();
    board.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    board.setVisible(true);
}//GEN-LAST:event_button1MouseClicked

private void theme_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theme_comboActionPerformed
// TODO add your handling code here:
    cms.changeTheme(theme_combo.getSelectedItem().toString().trim());
    dispose();
    new Roots().setVisible(true);
}//GEN-LAST:event_theme_comboActionPerformed

private void button_addCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addCustomerMouseEntered
// TODO add your handling code here:
    button_addCustomer.setBackground(cms.light3);
    button_addCustomer.setForeground(Color.WHITE);
}//GEN-LAST:event_button_addCustomerMouseEntered

private void button_addCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addCustomerMouseExited
// TODO add your handling code here:
    button_addCustomer.setBackground(cms.light2);
    button_addCustomer.setForeground(Color.WHITE);
}//GEN-LAST:event_button_addCustomerMouseExited

private void button_addCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addCustomerMouseClicked
// TODO add your handling code here:
    new AddCustomer(this, rootPaneCheckingEnabled).setVisible(true);
}//GEN-LAST:event_button_addCustomerMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        Dashboard db=new Dashboard();
        db.bill_type.setText("B2B");
        db.bill_type.setToolTipText("You have selected Business to Business");
        db.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        db.setVisible(true);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Dashboard db=new Dashboard();
        db.bill_type.setText("B2C");
        db.bill_type.setToolTipText("You have selected Business to Customer");
        db.setExtendedState(JFrame.MAXIMIZED_BOTH);
        db.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new CommonMethodClass().getThemeColors("Pale Blue");
                new Roots().setVisible(true);
            }
        });
         
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel button1;
    public javax.swing.JLabel button_addCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox theme_combo;
    // End of variables declaration//GEN-END:variables
}
